# Generated by Django 5.0.7 on 2024-08-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_aluno_curso_disciplina_delete_message_aluno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(to='chatbot.disciplina'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
